### ISSUE TITLE
Some questions for help

### ISSUE THREAD

**Issue by Jayce1932** [francisco-lai/LB-DNA#1]
Hi, thank you so much for sharing this code, I learned a lot from it. I wonder if you could share some more about the physics behind the code, for example, how do you calculate conductance for different calctypes(voltage probe or dephasing probe) in main.m, sincerely hope you can share some books or paper.

**Comment by francisco-lai** [comment]
Hey! Sorry for the late reply, but this code is still being fixed. There are a few bugs on it that I am still trying to fix. This is based on 'Spin-dependent electron transport in protein-like single-helical molecules' Ai-Min Guo and Qing-Feng Sun, PNAS 2014. I use the Landauer Buttiker Probe technique used in 'ProbeZT: Simulation of transport coefficients of molecular electronic
junctions under environmental effects using Büttiker’s probes' - Roman Korol, Michael Kilgour, Dvira Segal, CPC 2019. At the moment, only the voltage probe is working. Let me know if you have any questions!
